### ISSUE TITLE
TODO for v3.3

### ISSUE THREAD

**Issue by zwcloud** [zwcloud/MeshTerrainEditor-issues#16]
- [x] Set minimal horizontal vertex count to 3 when converting terrain/mesh to mesh-terrain: https://github.com/zwcloud/MeshTerrainEditor-issues/issues/11#issuecomment-399851768
- [x] Add a link to MTE_ReadMe.htm and force it to be opened by the browser, advised by [David Lieder](http://www.davidlieder.com)
   > The ReadMe is a great help document, but there are no links to it in the menu.   
   > At the very least you could put a hyperlink to it in the menu of the editor, like:  
   > Window/MTE/Documentation  
   > and force it to open in the browser (like Chrome or Firefox).
- [x] Change menu item from `MTE` to `Mesh Terrain Editor`, advised by David Lieder
   > the name of the asset is "Mesh Terrain Editor" and it is difficult to find "MTE" in the editor menus when a person is actually looking for "Mesh Terrain Editor".

**Comment by zwcloud** [comment]
Optionally, 

- [ ] Create a custom  "welcome" window with links to your documentation.

https://assetstore.unity.com/packages/tools/gui/publisher-window-welcome-screen-asset-store-tools-81067
