### ISSUE TITLE
TODO list of texture array based mesh-terrain solution (stable version)

### ISSUE THREAD

**Issue by zwcloud** [zwcloud/MeshTerrainEditor-issues#199]
- [ ] statistis on creator and converter UI
- [ ] more explict texel density calculation
- [ ] per-layer tilling material properties
