### ISSUE TITLE
TODO for v3.3.4

### ISSUE THREAD

**Issue by zwcloud** [zwcloud/MeshTerrainEditor-issues#48]
- [x] Check thoroughly and fix compatibility issues on Unity 2018.3
- [x] Add documentation on activation window
- [x] Add documentation on menu items
- [x] Update documentation: add a FAQ for https://github.com/zwcloud/MeshTerrainEditor-issues/issues/11#issuecomment-399838224
- [x] Better package organization: merge all content into one single *.unitypackage file. This should fix script missing issues like #50
